name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-on-PR:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy test environment variables
        run: |
          cp example.env .env
          sed -i 's/8080/8180/g' .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      
      - name: Build apps
        run: yarn turbo run build --color --concurrency=5

      - name: Run dev server
        run: bash e2e/support/run-e2e-docker-env.sh
      
      - name: Wait for OpenMRS instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8180/openmrs/login.htm)" != "200" ]]; do sleep 10; done

      - name: Run E2E tests
        run: yarn test-e2e

      - name: Stop dev server
        if: "!cancelled()"
        run: docker stop $(docker ps -a -q)

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  test-on-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    timeout-minutes: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy test environment variables
        run: |
          cp example.env .env
          sed -i 's/8080/8180/g' .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      
      - name: Build apps
        run: yarn turbo run build --color --concurrency=5

      - name: Run dev server
        run: bash e2e/support/run-e2e-docker-env.sh

      - name: Wait for OpenMRS instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8180/openmrs/login.htm)" != "200" ]]; do sleep 10; done

      - name: Run E2E tests
        run: yarn test-e2e

      - name: Upload report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
